#!/bin/bash

cd "$(dirname "$0")"

declare -i fail
for input in input.*.cg; do
    base=${input##input}; base=${base%%cg}
    ../src/divvun-suggest --json generator.hfstol errors.xml \
                          < "${input}" \
                          > output"${base}"json \
                          2>output"${base}"err
    if ! diff expected"${base}"json output"${base}"json; then
        echo "stdout differs for ${base}"
        (( fail++ ))
    fi
    if ! diff expected"${base}"err output"${base}"err; then
        echo "stderr differs for ${base}"
        (( fail++ ))
    fi
done

exit ${fail}
