: 
"<)>"
	")" RPAREN @EOP <firstWord> <spaceBeforeParenEnd>
	")" RPAREN @EMO <firstWord> <spaceBeforeParenEnd>
"<.>"
	"." PUNCT <LastCohort>
:\n
:\n
"<Twas>"
	"be" V Pret "<was>" <firstWord> <firstWordOfParagraph>
		"it" Prn 3Sg Neut "<T>" <firstWord> <firstWordOfParagraph>
: 
"<bryllyg>"
	"bryllyg" A
:  
"<and>"
	"and" CC <doubleSpaceBefore>
: 
"<the>"
	"the" D
: 
"<slithy>"
	"slithy" A <LastCohort>
;	"slithy" V Inf
: 
