#!/bin/bash

set -e -u

cd "$(dirname "$0")"

../../src/divvun-blanktag blanktagger.hfst < input.cg > output.cg

diff expected.cg output.cg

../../src/divvun-blanktag blanktagger.hfst < input.ends.cg > output.ends.cg

diff expected.ends.cg output.ends.cg
