#+TITLE: divvun-suggest
#+STARTUP: showall

#+CAPTION: Build Status
[[https://travis-ci.org/unhammer/divvun-suggest][https://travis-ci.org/unhammer/divvun-suggest.svg]]

* Description

This program does FST lookup on forms specified as Constraint
Grammar format readings, and looks up error-tags in an XML file with
human-readable messages. It is meant to be used as a late stage of a
grammar checker pipeline. The main output format is JSON.

* Prerequisites

- gcc >=5.0.0 with libstdc++-5-dev (or similarly recent version of
  clang, with full C++11 support)
- libpugixml >=1.7.2
- libhfst >=3.9.0

Tested with gcc-5.2.0, gcc-5.3.1 and clang-703.0.29. On Mac OS X, the
newest XCode includes a modern C++ compiler.

If you can't easily install libpugixml, you can run
[[file:scripts/get-pugixml-and-build][scripts/get-pugixml-and-build]] which will download libpugixml into this
directory, build that (with cmake) and configure this program to use
that library. Alternatively, you can run ./configure with
--disable-xml if you don't care about human-readable error messages.

* Building

#+BEGIN_SRC sh
./autogen.sh
./configure  # optionally with argument --prefix=$HOME/my/prefix
make
make install # with sudo if you didn't specify a prefix
#+END_SRC


On OS X, you may have to do this:

#+BEGIN_SRC sh
sudo port install pugixml
export CC=clang CXX=clang++ "CXXFLAGS=-std=gnu++11 -stdlib=libc++"
./autogen.sh
./configure  LDFLAGS=-L/opt/local/lib # optionally with argument --prefix=$HOME/my/prefix
make
make install # with sudo if you didn't specify a prefix
#+END_SRC

* Usage

Takes two arguments: a generator FST (in HFST optimised lookup
format), and an error message XML file (see [[https://gtsvn.uit.no/langtech/trunk/langs/sme/tools/grammarcheckers/errors.xml][the one for Northern Saami]]
for an example), with input/output as stdin and stdout:

#+BEGIN_SRC sh
src/divvun-suggest --json generator-gt-norm.hfstol errors.xml < input > output
#+END_SRC

More typically, it'll be in a pipeline after various runs of =vislcg3=:

#+BEGIN_SRC sh
echo words go here | hfst-tokenise -wacku: tokeniser.pmhfst | … | vislcg3 … \
  | divvun-suggest --json generator-gt-norm.hfstol errors.xml
#+END_SRC

* Troubleshooting

If you get
: terminate called after throwing an instance of 'std::regex_error'
:   what():  regex_error
or
: util.hpp:36:19: fatal error: codecvt: No such file or directory
:  #include <codecvt>
:                    ^
: compilation terminated.
then your C++ compiler is too old. See [[./README.org::*Prerequisites][Prerequisites]].


* Progress [8/11]

This should:

- [X] read cg format
- [X] load errors.xml
- [X] load an hfstol bin
- [X] generate forms from CG-specified analyses
- [X] only generate forms if analyses have a certain tag (and don't send that tag to generator)
- [ ] possibly load some additional specification for how to extract forms from CG-format?
- [X] optionally output as JSON

Also TODO:

- [ ] better way to skip @FLAGDIACRITICS@ in generator [[file:src/suggest.cpp::if(symbol.size()>0%20&&%20symbol%5B0%5D!='@')%20{][output]]
- [ ] deal with subreadings
- [X] input format needs to show where we have (and don't have) blanks
- [X] deal with the new blank format given by hfst-tokenise (and
  remove old blank hacks)
- [ ] handle &DELETE nicely (UI also: sihko sáni = slett ordet)
