#!/bin/bash

set -e
if [[ ${BASH_VERSINFO[0]} -gt 4
   || ${BASH_VERSINFO[0]} -eq 4 && ${BASH_VERSINFO[1]} -ge 4 ]]; then
    set -u
    # With bash <4.4, using ${a[@]} or ${a[*]} with an array without
    # any assigned elements when the nounset option is enabled will
    # throw an unbound variable error; so don't -u there
fi

cd "$(dirname "$0")"/../..

check () {
    local -r n="$1"
    shift
    local -ra args=( "$@" )
    src/divvun-validate-pipespec test/checker/pipespec.xml
    (
        cd test/checker
        set -x
        ../../src/divvun-checker "${args[@]}" < input."$n".txt > output."$n".json
    )
    if ! diff test/checker/output."$n".json test/checker/expected."$n".json; then
        echo diff test/checker/output."$n".json test/checker/expected."$n".json
        exit 1
    fi
}

# Arg 1 is the name of test set; the rest of the args are passed to divvun-checker
check "$@"
