#!/bin/bash

set -e

cd "$(dirname "$0")"

export PYTHONPATH="../../python/build/lib.linux-x86_64-3.6:$PYTHONPATH"
export LD_LIBRARY_PATH="../../src/.libs:$LD_LIBRARY_PATH"

python3 test-python-bindings.py
