#!/bin/bash

set -u

set -e

cd "$(dirname "$0")"
log="$(pwd)"/run-lib.verboselog

destdir=$(mktemp -d -t divvun-suggest-test-lib.XXXXXXXXXX)
trap 'echo "${log}:"; cat "${log}"' ERR
trap 'rm -rf "${destdir}"' EXIT

prefconf="$(grep '^prefix=' ../../config.log)"
eval "${prefconf}"
if [[ ! -n "${prefix}" ]]; then
    echo "Couldn't get prefix from config.log – not configured correctly?"
    exit 1
fi
export prefix
(
    cd ../..
    make --quiet install DESTDIR="${destdir}" &>"${log}"
)

ls "${destdir}/${prefix}"/include/divvun/checker.hpp >/dev/null

git --work-tree="${destdir}" checkout HEAD -- examples
cp ../checker/sme.zcheck "${destdir}"/examples/using-checker-lib-from-cpp/

cd "${destdir}"/examples/using-checker-lib-from-cpp/

export LDFLAGS="-L${destdir}/${prefix}/lib -ldivvun -lcg3 -lhfst -larchive ${LDFLAGS:-}" \
       CXXFLAGS="-I${destdir}/${prefix}/include ${CXXFLAGS:-}"                           \
       LD_LIBRARY_PATH="${destdir}/${prefix}/lib:${destdir}/${prefix}/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"
./autogen.sh &>"${log}"
./configure  &>"${log}"
make -j3     &>"${log}"

input="seammas ballat ođđa dieđuiguin"
expected='{"errs":[["dieđuiguin",20,30,"msyn-valency-loc-com","msyn thingy",["diehtukorrekt"]]],"text":"seammas ballat ođđa dieđuiguin"}
form=dieđuiguin beg=20 end=30 err=msyn-valency-loc-com msg=msyn thingy rep=diehtukorrekt'
echo "${input}"                                                             \
    | src/using-checker -a sme.zcheck -n smegram                            \
    | diff <(printf "%s\n" "${expected}") -
