#!/bin/bash

if ! command -V git >/dev/null 2>/dev/null; then
    # We use git to make pristine copy of ./examples; skip if we don't have git (e.g. package builders)
    echo "No git, skipping run-lib test"
    exit 77
fi

set -u

set -e

cd "$(dirname "$0")"
log="$(pwd)"/run-lib.verboselog

destdir=$(mktemp -d -t divvun-suggest-test-lib.XXXXXXXXXX)
trap 'echo "${log}:"; cat "${log}"' ERR
trap 'rm -rf "${destdir}"' EXIT

echo "Testing checker as lib ..." &>"${log}"

prefconf="$(grep '^prefix=' ../../config.log)"
eval "${prefconf}"
if [[ ! -n "${prefix}" ]]; then
    echo "Couldn't get prefix from config.log – not configured correctly?"
    exit 1
fi
(
    cd ../..
    make --quiet install DESTDIR="${destdir}" &>>"${log}"
)

ls "${destdir}/${prefix}"/include/divvun/checker.hpp &>>"${log}"

git --work-tree="${destdir}" checkout HEAD -- examples
cp sme.zcheck "${destdir}"/examples/using-checker-lib-from-cpp/

cd "${destdir}"/examples/using-checker-lib-from-cpp/

# NB: Test in Travis before and after changing the following paragraph:
export LDFLAGS="-L${destdir}/${prefix}/lib -lcg3 -lhfst -larchive ${LDFLAGS:-}" \
       CXXFLAGS="-I${destdir}/${prefix}/include ${CXXFLAGS:-}"                           \
       DYLD_LIBRARY_PATH="${destdir}/${prefix}/lib:${DYLD_LIBRARY_PATH:-}"
DYLD_FALLBACK_LIBRARY_PATH="${destdir}/${prefix}/lib:${DYLD_FALLBACK_LIBRARY_PATH:-}"
LD_LIBRARY_PATH="${destdir}/${prefix}/lib:${destdir}/${prefix}/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"

# Without the following, Fedora fails if older versions are installed in ${prefix}:
# No one knows why: https://stackoverflow.com/q/30939710/69663
export LDFLAGS="-Wl,-rpath,${destdir}/${prefix}/lib ${LDFLAGS:-}"


./autogen.sh &>>"${log}"
if ! ./configure  &>>"${log}"; then
    cat config.log
    exit 1
fi
make -j3     &>>"${log}"

input="seammas ballat ođđa dieđuiguin"
expected='{"errs":[["dieđuiguin",20,30,"msyn-valency-loc-com","msyn thingy",["diehtukorrekt"]]],"text":"seammas ballat ođđa dieđuiguin"}
form=dieđuiguin beg=20 end=30 err=msyn-valency-loc-com msg=msyn thingy rep=diehtukorrekt'
echo "${input}"                                                             \
    | src/using-checker -a sme.zcheck -n smegram                            \
    | diff <(printf "%s\n" "${expected}") -
