"<davasguvlui>"
	"davasguvlui" ?
	"davás guvlui" Adv <W:9.29688> <WA:15.2969> <spelled> "<davás guvlui>" &SUGGESTWF &typo
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "<darvasgovlui>" &SUGGESTWF &typo
		"darvvas" A Cmp
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "<davrasgovlui>" &SUGGESTWF &typo
		"davrras" A Cmp
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "<eavasgovlui>" &SUGGESTWF &typo
		"eavas" A Cmp
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "<daŋasgovlui>" &SUGGESTWF &typo
		"daŋas" N Cmp
:\n

