"<Dat>"
	"dat" Pron <smj> <smj> Dem Sg Nom <W:0.0>
: 
"<ij>"
	"ij" V IV Neg Ind Prs Sg3 <W:0.0> @+FAUXV &msyn-sme_interference_neg ID:2 R:$2:3 R:RIGHT:3
	"ij" V IV Neg Ind Prt Sg3 <W:0.0> @+FAUXV &SUGGEST ID:2 R:$2:3
: 
"<vuojnnum>"
	"vuojnnet" N <smj> <smj> Sg Nom <W:0.0> ID:3
	"vuojnnet" V IV Actio Nom <W:0.0> @X ID:3
	"vuojnnet" V IV PrfPrc <W:0.0> @-FMAINV COERROR &msyn-sme_interference_neg ID:3
	"vuojnnet" V COERROR Der/PassS V IV Ind ConNeg &SUGGEST ID:3
	"vuojnnut" Ex/V IV Der/NomAct N <smj> <smj> Sg Nom <W:0.0> ID:3
	"vuojnnut" V IV Actio Nom <W:0.0> @X ID:3
	"vuojnnut" V IV PrfPrc <W:0.0> @-FMAINV COERROR &msyn-sme_interference_neg ID:3
: 
