"<davasguvlui>"
	"davasguvlui" ?
	"davás guvlui" Adv <W:9.29688> <WA:15.2969> <spelled> "davás guvlui"S SUGGESTWF &typo
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "darvasgovlui"S SUGGESTWF &typo
		"darvvas" A Cmp
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "davrasgovlui"S SUGGESTWF &typo
		"davrras" A Cmp
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "eavasgovlui"S SUGGESTWF &typo
		"eavas" A Cmp
	"govlut" V Der/NomAg N Sem/Hum Sg Ill <W:30.2969> <WA:29.2969> <spelled> "daŋasgovlui"S SUGGESTWF &typo
		"daŋas" N Cmp
:\n

