#!/bin/bash

if test -z "$srcdir" ; then
    echo run from make check or set srcdir=.
    exit 1
fi
set -u

#cd "$(dirname "$0")" || exit 1

declare -i fail=0
for input in "$srcdir"/input.*.cg.genall; do
    base=$(basename $input)
    base=${base##input}; base=${base%%cg.genall}
    ../../src/divvun-suggest --generate-all bil.hfstol \
                          < "${input}" \
                          > output"${base}"cg \
                          2>output"${base}"err
    if ! diff "$srcdir"/expected"${base}"cg output"${base}"cg; then
        echo "stdout differs for ${base}"
        (( fail++ ))
    fi
    if ! diff "$srcdir"/expected"${base}"err output"${base}"err; then
        echo "stderr differs for ${base}"
        (( fail++ ))
    fi
done

if test "$fail" -gt 0 ; then
    exit 1
fi
