#!/bin/bash

if test -z "$srcdir" ; then
    echo call from make check or set srcdir=.
    exit 1
fi

set -u

#cd "$(dirname "$0")" || exit 1

declare -i fail=0

for xml in "$srcdir"/errors*.xml; do
    if ! ../../src/divvun-validate-suggest "${xml}"; then
        echo "${xml} should validate, but didn't"
        (( fail++ ))
    fi
done

for xml in "$srcdir"/invalid*.xml; do
    if ../../src/divvun-validate-suggest "${xml}"; then
        echo "${xml} shouldn't validate, but did"
        (( fail++ ))
    fi
done

if test "$fail" -gt 0 ; then
    exit 1
fi
