#!/bin/bash

set -e -u

cd "$(dirname "$0")/.."

ver=1.7
pkg=pugixml-"${ver}"
url=http://github.com/zeux/pugixml/releases/download/v"${ver}"/"${pkg}".tar.gz
if command -V wget >/dev/null 2>/dev/null; then
    wget -nc "${url}"
else
    curl "${url}" -O "${pkg}".tar.gz
fi
tar xzf "${pkg}".tar.gz
( cd "${pkg}" && cmake scripts && make )

./autogen.sh
./configure --disable-checker CXXFLAGS=-fPIC CPPFLAGS=-I"$(pwd)"/"${pkg}"/src/ LDFLAGS=-L"$(pwd)"/"${pkg}" "$@"
make -j3
make test VERBOSE=true
