#!/bin/bash

[[ "${BASH_SOURCE[0]}" != "${0}" ]] || set -eu

# Would like to use gold, but it links divvun-checker to (relative path) ./.libs/libdivvun-suggest.so ?
false && command -V ld.gold && export CXXFLAGS="-fuse-ld=gold ${CXXFLAGS:-}"
export CXXFLAGS="-ggdb3 -O0 -fPIC ${CXXFLAGS:-}"
export CPPFLAGS=-DDEBUG

# for make check:
export VERBOSE=1

bake () {
    if command -V bear &>/dev/null; then
        bear make "$@"
    else
        make "$@"
    fi
}

build () {
    ./autogen.sh
    ./configure --prefix="$HOME"/PREFIX/gtd-gc --with-trang="$HOME"/.jedit/jars/trang.jar --enable-checker
    bake -j3
    bake -j3 install
    for prog in "$HOME"/PREFIX/gtd-gc/bin/divvun*; do
        PATH="$HOME/PREFIX/gtd-gc/bin/:$PATH"                 \
            help2man -N                                       \
            -S 'divvun-gramcheck'                             \
            -n 'This application is part of divvun-gramcheck' \
            "${prog##*/}"                                     \
            > src/"${prog##*/}".1
    done
    bake -j3 check
    git ls-files src | grep pp$ | grep -ve mapbox -e cxxopts | xargs -I{} clang-tidy --checks='-*,modernize-*,-modernize-make-unique,-modernize-pass-by-value,-modernize-raw-string-literal' {} -- -Isrc -std=c++11
}

[[ "${BASH_SOURCE[0]}" != "${0}" ]] || build
