#!/bin/bash

set -e -u

TRGDIR="$(pwd)"
export TRGDIR

munge_path () {
    # Bug in apertium-all-dev.tar.gz?
    # Some libs refer to /opt/osx, others have no paths
    sed -e 's%^/opt/osx/%/usr/local/%' \
        -e 's%^lib%/usr/local/lib/lib%'
}

relativise_mac_lib () {
    lib="$1"
    name="$(basename "${lib}")"
    rellib="${TRGDIR}/${name}"
    if [[ -e ${rellib} ]]; then
        echo "${name} already exists in ${TRGDIR}, not reprocessing"
        return 0
    elif [[ ! -e ${lib} ]]; then
        echo "WARNING: ${lib} doesn't exist"
        return 1
    fi
    echo "Processing ${lib}"
    ls -lah "${lib}"
    cp -L "${lib}" "${rellib}"
    chmod 755 "${rellib}"
    # Assumes no deps have spaces in their paths
    deps=( $(otool -L "${rellib}" | awk '$0 ~/^\t/ && $1 && $1!~"/usr/lib" {print $1}' ) )
    for d in "${deps[@]}"; do
        dname="$(basename "$d")"
        install_name_tool -change "$d" @loader_path/"${dname}" "${rellib}"
    done
    for d in "${deps[@]}"; do
        munged=$(munge_path <<< "$d")
        relativise_mac_lib "${munged}"
    done
}

relativise_mac_lib "$@"
