#!/bin/bash

set -e -u

if [[ ${COVERITY_SCAN_BRANCH} = 1 ]]; then
    echo 'On coverity_scan branch, not running usual travis build + test suite.'
    for f in cov-int/*log.txt; do
        test -f "$f" && echo "== $f ==" && cat "$f"
    done
    exit 0
fi

cd "$(dirname "$0")/.."

export PKG_CONFIG_PATH LD_LIBRARY_PATH DYLD_LIBRARY_PATH LDFLAGS CPPFLAGS

if [[ $TRAVIS_OS_NAME = osx ]]; then
    # Stuff from nightly goes in plain /usr/local:
    PKG_CONFIG_PATH="${PKG_CONFIG_PATH:-}:/usr/local/share/pkgconfig:/usr/local/lib/pkgconfig"
    ACLOCAL_PATH="${ACLOCAL_PATH:-}:/usr/local/share/aclocal"
    PATH="${PATH}:/usr/local/bin"

    brew update || brew update || true
    brew ls --versions pugixml    || brew install pugixml    || brew install pugixml
    brew ls --versions libarchive || brew install libarchive || brew install libarchive
    brew ls --versions swig       || brew install swig       || brew install swig
    brew ls --versions python3    || brew install python3    || brew install python3

    # brew puts pugixml/libarchive outside the regular paths:
    LDFLAGS="${LDFLAGS:-} -L/usr/local/Cellar/pugixml/1.8.1/lib/pugixml-1.8"
    LDFLAGS="${LDFLAGS:-} -L/usr/local/opt/libarchive/lib"
    CPPFLAGS="${CPPFLAGS:-} -I/usr/local/Cellar/pugixml/1.8.1/include/pugixml-1.8"
    CPPFLAGS="${CPPFLAGS:-} -I/usr/local/opt/libarchive/include"
    PKG_CONFIG_PATH="${PKG_CONFIG_PATH:-}:/usr/local/opt/libarchive/lib/pkgconfig"

    (
        # A travis-caching version of
        # http://apertium.projectjj.com/osx/install-nightly.sh
        WHERE='/usr/local'
        # Other locales may make Perl unhappy
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        mkdir -p "$HOME"/gtd-cache
        tarball="$HOME"/gtd-cache/apertium-all-dev.tar.bz2
        if [[ -f "${tarball}" ]]; then
            stat -f "Reusing cached %N from %Sm" "${tarball}" # assuming BSD stat
        else
            curl https://apertium.projectjj.com/osx/nightly/apertium-all-dev.tar.bz2 > "${tarball}"
        fi
        cd
        tar -jxf "${tarball}"
        cd apertium-all-dev
        (
            set +e
            find . -type f -name '*.la' -exec rm -fv '{}' \;
        )
        echo "Fixing hardcoded paths"
        FILES=$(grep -El '^#!/' $(grep -rl '/opt/osx' bin))
        FILES="$FILES $(grep -rl '/opt/osx' lib/pkgconfig)"
        for FILE in $FILES; do
            echo "Fixing $FILE"
            perl -pe "s@/opt/osx@$WHERE@g;" -i.orig "$FILE"
        done
        sudo mkdir -p "$WHERE/"
        sudo cp -af ./* "$WHERE/"
        sudo chmod -R uga+r "$WHERE"
    )
else
    wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    sudo apt-get -f install -y libhfst-dev libcg3-dev hfst-ospell-dev swig3.0 libpython3-dev
    if [[ ${CC} = gcc && ${CXX} = g++ ]]; then
        export CC=gcc-5
        export CXX=g++-5
    fi
fi

./autogen.sh
./configure "$@"
make -j3
make check VERBOSE=true
sudo make install

if [[ $TRAVIS_OS_NAME = osx && $CC = clang ]]; then
    mkdir rellibs
    (
        cd rellibs
        find /usr/local/lib/ -name '_libdivvun*' -print0 | while read -r -d '' lib; do
            bash ../scripts/relativise_mac_libs "${lib}"
        done
    )
    zip -r ./rellibs.zip ./rellibs
    curl --upload-file ./rellibs.zip https://transfer.sh/rellibs.zip
fi
