#!/bin/bash

set -e -u

if [[ ${COVERITY_SCAN_BRANCH} = 1 ]]; then
    echo 'On coverity_scan branch, not running usual travis build + test suite.'
    for f in cov-int/*log.txt; do
        test -f "$f" && echo "== $f ==" && cat "$f"
    done
    exit 0
fi

cd "$(dirname "$0")/.."

export PKG_CONFIG_PATH LD_LIBRARY_PATH DYLD_LIBRARY_PATH LDFLAGS CPPFLAGS

if [[ $TRAVIS_OS_NAME = osx ]]; then
    # brew puts pugixml/libarchive outside the regular paths:
    LDFLAGS="${LDFLAGS:-} -L/usr/local/Cellar/pugixml/1.8.1/lib/pugixml-1.8"
    LDFLAGS="${LDFLAGS:-} -L/usr/local/opt/libarchive/lib"
    CPPFLAGS="${CPPFLAGS:-} -I/usr/local/Cellar/pugixml/1.8.1/include/pugixml-1.8"
    CPPFLAGS="${CPPFLAGS:-} -I/usr/local/opt/libarchive/include"
    PKG_CONFIG_PATH="${PKG_CONFIG_PATH:-}:/usr/local/opt/libarchive/lib/pkgconfig"

    (
        # A travis-caching version of
        # http://apertium.projectjj.com/osx/install-nightly.sh
        WHERE='/usr/local'
        # Other locales may make Perl unhappy
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        mkdir -p /tmp/aad.$$
        cd /tmp/aad.$$
        mkdir -p "$HOME"/gtd-cache
        tarball="$HOME"/gtd-cache/apertium-all-dev.tar.bz2
        if [[ -f "${tarball}" ]]; then
            stat -f "Reusing cached %N from %Sm" "${tarball}" # assuming BSD stat
        else
            curl https://apertium.projectjj.com/osx/nightly/apertium-all-dev.tar.bz2 > "${tarball}"
        fi
        tar -jxf "${tarball}"
        cd apertium-all-dev
        (
            set +e
            find . -type f -name '*.la' -exec rm -fv '{}' \;
        )
        echo "Fixing hardcoded paths"
        FILES=$(egrep -l '^#!/' $(grep -rl '/opt/osx' bin))
        FILES="$FILES $(grep -rl '/opt/osx' lib/pkgconfig)"
        for FILE in $FILES; do
            echo "Fixing $FILE"
            perl -pe "s@/opt/osx@$WHERE@g;" -i.orig "$FILE"
        done
        sudo mkdir -p "$WHERE/"
        sudo cp -af ./* "$WHERE/"
        sudo chmod -R uga+r "$WHERE"
        cd /tmp
        rm -rf /tmp/aad.$$
    )
fi

./autogen.sh
./configure --enable-checker
make -j3
make check VERBOSE=true

make distclean

./autogen.sh
./configure --disable-checker
make -j3
make check VERBOSE=true
