.TH DIVVUN-NORMALISER "1" "April 2021" "divvun-normaliser" "User Commands"
.SH NAME
divvun-normaliser \- This application is part of divvun-gramcheck
.SH DESCRIPTION
.SS "Usage:"
.IP
divvun\-normaliser [OPTION...]BIN \- use an FST to normalise texts for TTS
.TP
\fB\-a\fR, \fB\-\-analyser\fR BIN
FST for analysis
.TP
\fB\-i\fR, \fB\-\-input\fR FILE
Input file (UNIMPLEMENTED, stdin for now)
.TP
\fB\-o\fR, \fB\-\-output\fR FILE
Output file (UNIMPLEMENTED, stdout for now)
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose
.TP
\fB\-V\fR, \fB\-\-version\fR
Version information
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
