#!/bin/bash

if test -z "$srcdir" ; then
    echo call this from make check or set srcdir=.
    exit 1
fi

set -e
if [[ ${BASH_VERSINFO[0]} -gt 4
   || ${BASH_VERSINFO[0]} -eq 4 && ${BASH_VERSINFO[1]} -ge 4 ]]; then
    set -u
    # With bash <4.4, using ${a[@]} or ${a[*]} with an array without
    # any assigned elements when the nounset option is enabled will
    # throw an unbound variable error; so don't -u there
fi

#cd "$(dirname "$0")"/../.

check () {
    local -r n="$1"
    shift
    local -ra args=( "$@" )

    (
        #cd test/cgspell
        set -x
        ../../src/divvun-cgspell -l analyser.hfstol -m "$srcdir"/errmodel.hfst \
            "${args[@]}" < "$srcdir"/input."$n" > output."$n"
    )
    if ! diff output."$n" "$srcdir"/expected."$n"; then
        echo diff test/cgspell/output."$n" test/cgspell/expected."$n"
        exit 1
    fi
}

# Arg 1 is the name of test set; the rest of the args are passed to divvun-cgspell
check "$@"
