#!/bin/bash

set -e -u

cd "$(dirname "$0")"/../..

check () {
    n="$1"
    shift
    args=( "$@" )
    (
        cd test/cgspell
        set -x
        ../../src/divvun-cgspell -l analyser.hfstol -m errmodel.hfst "${args[@]}" < input."$n" > output."$n"
    )
    if ! diff test/cgspell/output."$n" test/cgspell/expected."$n"; then
        echo diff test/cgspell/output."$n" test/cgspell/expected."$n"
        exit 1
    fi
}

# Arg 1 is the name of test set; the rest of the args are passed to divvun-cgspell
check "$@"
