name: libdivvun CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
           sudo apt-get -qy update
           sudo apt-get -qfy install wget ca-certificates
           wget -q https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
           sudo apt-get -qfy install --no-install-recommends autotools-dev gawk hfst-ospell-dev libarchive-dev libcg3-dev libhfst-dev libpugixml-dev libutfcpp-dev libxml2-utils pkg-config python3-dev python3-setuptools swig zip
    - name: autoreconf
      run: autoreconf -fvi
    - name: configure
      run: ./configure --enable-checker --enable-cgspell --enable-python-bindings
    - name: build
      run: make -j V=1 VERBOSE=1
    - name: tests
      run: make test V=1 VERBOSE=1
    - name: make install
      run: sudo make install
